### PR TITLE
Remove usage of dollar sign

### PR DESCRIPTION
**Pull request by pcambra**
I think it has a special meaning for ruby, a global variable or something, I'm guessing is a PHPism in here :)

### CODE REVIEW

**Comment by lewisnyman** [comment]
I had to revert this because it breaks the buildcompanies task:

```
Message:
    Command failed: ./companies.rb:51:in `ensure_company': undefined local variable or method `companies_info' for main:Object (NameError)
	from ./companies.rb:64:in `block in <main>'
	from ./companies.rb:61:in `each'
	from ./companies.rb:61:in `<main>'

Details:
    killed: false
    code: 1
    signal: null
    stdout: 
    stderr: ./companies.rb:51:in `ensure_company': undefined local variable or method `companies_info' for main:Object (NameError)
	from ./companies.rb:64:in `block in <main>'
	from ./companies.rb:61:in `each'
	from ./companies.rb:61:in `<main>'
```

Hopefully we will have TravisCI integration soon

**Comment by pcambra** [comment]
Ouch, this is being used as global at the end, I'll give another try to remove the need of a global.

What needs to happen to have TravisCI? happy to help.

**Comment by pcambra** [comment]
Can we reopen this? I still think it needs to happen

**Comment by lewisnyman** [comment]
Sure let's do that, I don't know if it's possible to remerge in the same pull request? Maybe we have to open a new PR?

**Comment by pcambra** [comment]
I'm testing it, I'll open a new PR with this

**Pull request merged**
