### PR TITLE
Development branch is now 8.4.x

### PR DESCRIPTION
**Pull request by claudiu-cristea**

### CODE REVIEW

**Comment by lauriii** [comment]
Thank you!

**Comment by claudiu-cristea** [comment]
@lauriii, strange, now http://www.drupalcores.com/ looks broken. But I tested this PR locally and worked nice

**Comment by gnuget** [comment]
The same happened when I worked on #89 and If a remember correctly is because to is necessary to do a "git fetch" manually so when the script tries to change to 8.4.x the branch actually exists. 

hope this helps.

**Comment by claudiu-cristea** [comment]
@gnuget, yes, that makes sense. I opened #97 to fix this.

**Comment by fuzzbomb** [comment]
@claudiu-cristea I'm proposing a different approach in #107, so we don't have to update the branch number every 6 months.  Instead, we would just use whatever is marked as the default branch in the  Drupal core repo.

**Pull request merged**
