### PR TITLE
upgrade to latest dev build.

### PR DESCRIPTION
**Pull request by martinfrances107**
Drupal 8.6.x is now the latest dev branch .. and 8.4.x changing very slowly if at all maybe it is time to upgrade?

### CODE REVIEW

**Comment by timmillwood** [comment]
The Travis fails look unrelated, it'd be nice to get this fix in place and have drupalcores up and running again.

**Comment by lauriii** [comment]
This PR is still missing some of the changes required on the version bump. See this PR for example of what is required https://github.com/lauriii/drupalcores/pull/105/files

**Comment by borisson** [comment]
This can be closed, now that #107 is in.

**Comment by alexpott** [comment]
Fixed in #114

**Pull request closed without merging**
