### PR TITLE
Development branch is now 8.5.x

### PR DESCRIPTION
**Pull request by claudiu-cristea**

### CODE REVIEW

**Comment by wimleers** [comment]
Failed with syntax error:
```
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
```

That seems to not have been introduced by this PR… so why this would fail, is a mystery to me.

**Comment by fuzzbomb** [comment]
@claudiu-cristea I'm proposing a different approach in #107, so we don't have to update the branch number every 6 months. Instead, we would just use whatever is marked as the default branch in the Drupal core repo. Would you like to review it?

**Comment by borisson** [comment]
Let's change this to the recently opened 8.6.x instead of 8.5 until #107 is in.

**Comment by borisson** [comment]
I think we can close this issue in favor of #108 or #107.

**Comment by borisson** [comment]
This can be closed, now that #107 is in.

**Comment by alexpott** [comment]
Fixed in #114

**Pull request closed without merging**
