### PR TITLE
Fetch remote before git checkout & log

### PR DESCRIPTION
**Pull request by claudiu-cristea**

### CODE REVIEW

**Comment by lauriii** [comment]
It seems like the git fetch doesn't support git-dir flag causing following error
```
[09:57:10] Starting 'buildjson'...
error: unknown option `git-dir=../drupalcore/.git'
```

**Comment by claudiu-cristea** [comment]
@lauriii. last commit should fix that

**Comment by lauriii** [comment]
Thanks for this fix! Makes bumping to a new minor version easier

**Comment by claudiu-cristea** [comment]
Hm. Still not work http://www.drupalcores.com/

**Pull request merged**
