### PR TITLE
Change name mapping of chx from not specified to charlie-chx-negyesi

### PR DESCRIPTION
**Pull request by drupal-daffie**
The old accounts of Charlie Negyesi are now mapped to "Not specified". I think this not OK. Charlie is a member of the Drupal community and should be treated with the same minimum level of respect as any other member of our community. @lauriii: You are a core committer of the Drupal project, that is a very high leadership position in our community. Could you treat Charlie with the respect that every member of our community deserves. Thanks.

### CODE REVIEW

**Comment by lauriii** [comment]
This was specifically implemented per his request on https://github.com/lauriii/drupalcores/issues/99. If he wishes his old commits to be visible again, I'm happy to help make that so.

**Comment by drupal-daffie** [comment]
I did not see that request. I apologize if I offended you in any way. I like chx and to me it is/was not respectful to him. I guess that both sides in the whole chx affair were not happy. He is now back for a while. Maybe better just to put him back on the list, without asking him/reminding him about the painful affair. I let you can make that judgement call.

**Comment by chx** [comment]
Let's remove the not specified mapping but let's not merge the two accounts. Thanks.

**Comment by alexpott** [comment]
@chx is the latest change I made to this what you'd like?

**Comment by chx** [comment]
Looks good, thanks.

**Pull request merged**
